# Generated by Django 3.2.5 on 2021-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("autres", "Autres"),
                            ("base-de-donnees", "Base de données"),
                            (
                                "developpement-back-end",
                                "Développement Back-end",
                            ),  # noqa: E501
                            (
                                "developpement-front-end",
                                "Développement Front-end",
                            ),  # noqa: E501
                            (
                                "developpement-full-stack",
                                "Développement Full-Stack",
                            ),  # noqa: E501
                            ("gestion-de-projet", "Gestion de projet"),
                            (
                                "gestion-de-site-reseaux-sociaux",
                                "Gestion de site & réseaux sociaux",
                            ),
                            ("marketing", "Marketing"),
                            ("produit", "Produit"),
                            ("pedagogie-formation", "Pédagogie & formation"),
                            ("seo-sea", "SEO/SEA"),
                            ("support", "Support"),
                            ("systeme", "Système"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="compétences",
                    ),
                ),
            ],
        ),
    ]
